---
- name: Get timedate info from remote hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Get current time on the host
      command: date
      register: current_time

    - name: Show the time from remote host
      debug:
        msg: "The current time on {{ inventory_hostname }} is: {{ current_time.stdout }}"
